version: '2.4'

services:
  hh_tracker:
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: hh_tracker:latest
    container_name: hh_tracker
    restart: always
    logging:
      driver: "json-file"
    environment:
        TG_TOKEN: "${TG_TOKEN}"
        BOT_ADMIN: "${BOT_ADMIN}"
    volumes:
      - ./run_data:/opt/hh_tracker/run_data
